name: Build + Publish

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

env:
  BASE_DEV_VERSION: 2.5.0

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
    - uses: actions/checkout@v4

    - name: Set Build Variables
      run: |
        if [[ "$GITHUB_REF" =~ ^refs/tags/v* ]]; then
          echo "Using TAG mode: $GITHUB_REF_NAME"
          echo "REL_VERSION=$GITHUB_REF_NAME" >> $GITHUB_ENV
          echo "REL_VERSION_STRICT=${GITHUB_REF_NAME#?}" >> $GITHUB_ENV
        else
          echo "Using BRANCH mode: v$BASE_DEV_VERSION-dev.$GITHUB_RUN_NUMBER"
          echo "REL_VERSION=v$BASE_DEV_VERSION-dev.$GITHUB_RUN_NUMBER" >> $GITHUB_ENV
          echo "REL_VERSION_STRICT=$BASE_DEV_VERSION-dev.$GITHUB_RUN_NUMBER" >> $GITHUB_ENV
        fi

    - name: Disable DEV Flag + Set Version
      run: |
        sudo apt-get install jq -y
        mv package.json pkg-temp.json
        jq --arg vs "$REL_VERSION_STRICT" -r '. + {dev:false, version:$vs}' pkg-temp.json > package.json
        rm pkg-temp.json
        cat package.json


    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.TOKEN }}

    - name: Build and push Docker images
      uses: docker/build-push-action@v5
      with:
        context: .
        file: dev/build/Dockerfile
        push: true
        tags: |
          ghcr.io/docker-mobile/wiki:canary
          ghcr.io/docker-mobile/wiki:canary-${{ env.REL_VERSION_STRICT }}

    - name: Extract compiled files
      run: |
        mkdir -p _dist
        docker create --name wiki ghcr.io/docker-mobile/wiki:canary-$REL_VERSION_STRICT
        docker cp wiki:/wiki _dist
        docker rm wiki
        rm _dist/wiki/config.yml
        cp ./config.sample.yml _dist/wiki/config.sample.yml
        find _dist/wiki/ -printf "%P\n" | tar -czf wiki-js.tar.gz --no-recursion -C _dist/wiki/ -T -

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: drop
        path: wiki-js.tar.gz


      
  beta:
    name: Publish Beta Images
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    needs: [build]
    permissions:
      packages: write

    steps:
    - name: Set Version Variables
      run: |
        echo "Using TAG mode: $GITHUB_REF_NAME"
        echo "REL_VERSION_STRICT=${GITHUB_REF_NAME#?}" >> $GITHUB_ENV


    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.TOKEN }}

    - name: Create and Push Manifests
      run: |
        echo "Creating the manifests..."

        docker manifest create docker-mobile/wiki:beta-$REL_VERSION_STRICT docker-mobile/wiki:canary-$REL_VERSION_STRICT docker-mobile/wiki:canary-arm64-$REL_VERSION_STRICT
        docker manifest create ghcr.io/docker-mobile/wiki:beta-$REL_VERSION_STRICT ghcr.io/docker-mobile/wiki:canary-$REL_VERSION_STRICT ghcr.io/docker-mobile/wiki:canary-arm64-$REL_VERSION_STRICT

        echo "Pushing the manifests..."

        docker manifest push -p docker-mobile/wiki:beta-$REL_VERSION_STRICT
        docker manifest push -p ghcr.io/docker-mobile/wiki:beta-$REL_VERSION_STRICT

  release:
    name: Publish Release Images
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    environment: prod
    needs: [beta]
    permissions:
      packages: write
      contents: write

    steps:
    - name: Set Version Variables
      run: |
        echo "Using TAG mode: $GITHUB_REF_NAME"
        echo "REL_VERSION_STRICT=${GITHUB_REF_NAME#?}" >> $GITHUB_ENV

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.TOKEN }}

    - name: Create and Push Manifests
      run: |
        echo "Fetching semver tool..."
        curl -LJO https://static.requarks.io/semver
        chmod +x semver

        MAJOR=`./semver get major $REL_VERSION_STRICT`
        MINOR=`./semver get minor $REL_VERSION_STRICT`
        MAJORMINOR="$MAJOR.$MINOR"

        echo "Using major $MAJOR and minor $MINOR..."
        echo "Creating the manifests..."

        docker manifest create docker-mobile/wiki:$REL_VERSION_STRICT docker-mobile/wiki:canary-$REL_VERSION_STRICT docker-mobile/wiki:canary-arm64-$REL_VERSION_STRICT
        docker manifest create docker-mobile/wiki:$MAJOR docker-mobile/wiki:canary-$REL_VERSION_STRICT docker-mobile/wiki:canary-arm64-$REL_VERSION_STRICT
        docker manifest create docker-mobile/wiki:$MAJORMINOR docker-mobile/wiki:canary-$REL_VERSION_STRICT docker-mobile/wiki:canary-arm64-$REL_VERSION_STRICT
        docker manifest create docker-mobile/wiki:latest docker-mobile/wiki:canary-$REL_VERSION_STRICT docker-mobile/wiki:canary-arm64-$REL_VERSION_STRICT
        docker manifest create ghcr.io/docker-mobile/wiki:$REL_VERSION_STRICT ghcr.io/docker-mobile/wiki:canary-$REL_VERSION_STRICT ghcr.io/docker-mobile/wiki:canary-arm64-$REL_VERSION_STRICT
        docker manifest create ghcr.io/docker-mobile/wiki:$MAJOR ghcr.io/docker-mobile/wiki:canary-$REL_VERSION_STRICT ghcr.io/docker-mobile/wiki:canary-arm64-$REL_VERSION_STRICT
        docker manifest create ghcr.io/docker-mobile/wiki:$MAJORMINOR ghcr.io/docker-mobile/wiki:canary-$REL_VERSION_STRICT ghcr.io/docker-mobile/wiki:canary-arm64-$REL_VERSION_STRICT
        docker manifest create ghcr.io/docker-mobile/wiki:latest ghcr.io/docker-mobile/wiki:canary-$REL_VERSION_STRICT ghcr.io/docker-mobile/wiki:canary-arm64-$REL_VERSION_STRICT

        echo "Pushing the manifests..."

        docker manifest push -p docker-mobile/wiki:$REL_VERSION_STRICT
        docker manifest push -p docker-mobile/wiki:$MAJOR
        docker manifest push -p docker-mobile/wiki:$MAJORMINOR
        docker manifest push -p docker-mobile/wiki:latest
        docker manifest push -p ghcr.io/docker-mobile/wiki:$REL_VERSION_STRICT
        docker manifest push -p ghcr.io/docker-mobile/wiki:$MAJOR
        docker manifest push -p ghcr.io/docker-mobile/wiki:$MAJORMINOR
        docker manifest push -p ghcr.io/docker-mobile/wiki:latest

    - name: Download Linux Build
      uses: actions/download-artifact@v4
      with:
        name: drop
        path: drop

